
<template>
    <q-dialog v-model="visible" full-height  @hide="$router.push('/')" >
      <q-card class="project-card text-center"  >
        <q-card-section class="bg-primary text-white " style="height:70px;"  v-close-popup>
            <h1>Schiphol indoor wayfinding</h1><q-btn class="absolute-right q-px-md" flat label="X" v-close-popup />
        </q-card-section>

        <q-card-section  style="max-height: calc(100% - 72px);" class="scroll"  >
            Schiphol Wayfinding exsists of serveral parts. Every part is a project by it self.
            <ul class="text-center" style="margin:20px auto 0 ; width: 380px;  list-style: decimal;">
                <li class="text-left" >A public Basemap IMDF</li>
                <li class="text-left" >Wayfinding API</li>
                <li class="text-left" >Mesh network</li>
                <li class="text-left" >BLE (Bluetooth beacons)</li>
                <li class="text-left" >Location tree</li>
            </ul>

            <h2>1 IMDF</h2>
            <h3> <a href="https://register.apple.com/resources/imdf/">Indoor Mapping Data Format</a> is becomming the new OGC standard for indoor GIS (At time of writing it still a <a href="https://www.ogc.org/standards/requests/202"> OGC request</a>) </h3>

            Apple designed a standard format for indoor buildings like airports called <a href="https://register.apple.com/resources/imdf/"> IMDF</a>. We worked closely with Apple Maps and <a href="https://www.safe.com/integrate/indoor-mapping-data-format-imdf/">Safe Software</a> (FME) to build the schiphol IMDF. The conversion from Schiphol data into IMDF is quite complex and ended up in a workspace that exsists of more than 500+ transfomers! During the project this decreased due to changes in the workflow. Schiphol maintained the data closer to the 'Aiport API'-model that is based on IMDF. In the end, less mappings (such as categories) were needed.
            <q-img alt="Apples IMDF on a iphones" style="max-height:50vh"   src="img/imdf_apple.jpg" />
            <div class="light"> IMDF seen on an Iphone at Apple maps</div>

            <h2>2 Wayfinding API</h2>
            <h3>A public endpoint for indoor routing and PointOfInterests</h3>

            In this project, is two-fold.

            <br><br>On onehand we build a new version of the API (Python) and dockerization. Developing is localy on a laptop. The data pushed into a git repostory, build and mounted on the staging environment. After unit-testing and endpoint testing its published to the <a href="https://www.google.com/search?q=green+blue+architecture">green-blue production</a>. The self-serve-units on schiphol in the terminal and airliners such as KLK make use of this routing. The API returns in OSRM format a walking line and times.

            <br><br>On the other hand creation of a GeoWeb (geocortex) website for maintaining the Points/Area of interests data. This data can be found in: Schiphol products (like mobile-apps, website), external Airliners (KLM, TUI) and other people.

            <br><br> See main page for a real life demo!
            <br><br>You can play with this data at <a href="https://developer.schiphol.nl/">developer.schiphol.nl</a>

            <h2>3 Mesh network</h2>
            <h3>The network behind the API</h3>

            To create an indoor 'route' network. We rendered (with FME) a so called mesh-network. It is corrected on the building orientations. Its is weighted in susch a way that it follows the original pricewinning analog schiphol wayfinding.
            It includes zones, such as: One-way-filters, different security clearances, dirty/clean passagiers and Internatial/Schengen

            <q-img alt="FME generated Meshnetwork on IMDF" style="max-height:50vh"   src="img/mesh.png" />
            <div class="light"> It is autogenerated on IMDF </div>

            <h2>4 Beacon BLE</h2>
            The beacon API let you enter Minor/Major/RSSI values, and as a result you get a lat-long position. This is not indoorpositioning (Iphone/Android) are way more advanced/better. But for tracking of assets within the terminal. The assets are  often connected to a LoRa network
            <q-img alt="Beacons bluetooth" style="max-height:50vh"   src="/img/beacons.png" />
            <div class="light"> Black is the 'blue dot' and thus the calculated position, based on the green bluetooth sensors. The blue cross is the realworld location </div>

            <h2>5 Location Tree</h2>
            This API is a uniform building/room/zones geolocator. There were so many different room definitions on the airport. Ground floor has already 5000+ rooms. The API lets link assets onto a room. They store a UUID. With the API you can get a JSON-repesentative or rendered image of the room, and

            <span class="foot-tags">Date: 2019 - 2020<br>
            Client: Royal Schiphol Group</span>
            <q-btn class="bg-primary text-white" flat label="Done" v-close-popup />
        </q-card-section>
      </q-card>
    </q-dialog>
</template>

<script>
export default { data () { return { visible: true } } }
</script>
